### ISSUE TITLE
[BUG] Car Jack Chance

### ISSUE THREAD

**Issue by RoyalRaid** [qbcore-framework/qb-vehiclekeys#125]
I'd like to have it so car jacking with no weapons is 100% success rate.
i changed Malee value to  = 1.00.

Once doing this im still unable to car jack NPC's.

Thanks

**Comment by tom-osborne** [comment]
@RoyalRaid yeah it looks like you can't carjack with melee since you cant aim your melee weapon at a vehicle. I'll have to think of a way around that.

For now, with the latest version, there is a config option to unlock all NPC vehicles. This allows you to carjack by pulling the NPC out of the vehicle. This might be what you are after.

**Comment by tom-osborne** [comment]
@RoyalRaid One thing that just came to mind... did you remove the melee weapon from the following section in the Config:
```lua
Config.NoCarjackWeapons = {
    "WEAPON_UNARMED",
    "WEAPON_Knife",
    "WEAPON_Nightstick",
    "WEAPON_HAMMER",
    "WEAPON_Bat",
    "WEAPON_Crowbar",
    "WEAPON_Golfclub",
    "WEAPON_Bottle",
    "WEAPON_Dagger",
    "WEAPON_Hatchet",
    "WEAPON_KnuckleDuster",
    "WEAPON_Machete",
    "WEAPON_Flashlight",
    "WEAPON_SwitchBlade",
    "WEAPON_Poolcue",
    "WEAPON_Wrench",
    "WEAPON_Battleaxe",
    "WEAPON_Grenade",
    "WEAPON_StickyBomb",
    "WEAPON_ProximityMine",
    "WEAPON_BZGas",
    "WEAPON_Molotov",
    "WEAPON_FireExtinguisher",
    "WEAPON_PetrolCan",
    "WEAPON_Flare",
    "WEAPON_Ball",
    "WEAPON_Snowball",
    "WEAPON_SmokeGrenade",
}
```
