### ISSUE TITLE
[BUG] Vehicle keys lock and unlock the vehicle at the same time.

### ISSUE THREAD

**Issue by PineappleOnMyPizza** [qbcore-framework/qb-vehiclekeys#154]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Try to lock the car
2. car locks and unlocks at the same time
3. Use this item '....' (item's name from shared.lua if applicable)
4. No errors

**Expected behavior**
toggle lock from unlock to lock

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by Re1ease** [comment]
I haven't been able to reproduce this. 
Please update qb-vehiclekeys to the latest version and try again.
Let me know if the issue remains afterwards.

**Comment by ChickenDipper1** [comment]
No able to reproduce, possibly another resource conflict?

**Comment by tom-osborne** [comment]
@PineappleOnMyPizza This sounds very much like a conflicting resource. Do you have any kind of vehicle locking resource like a key fob resource or some kind of custom plate resource?

If not, I would recommend turning off any resources you have added one by one and see if the problem is fixed. That way you can find which resource is causing an issue.
