### ISSUE TITLE
[BUG] Losing keys to current vehicle when restarting the script

### ISSUE THREAD

**Issue by W0lv3sxD** [qbcore-framework/qb-vehiclekeys#225]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Have a vehicle that is owned by you (you have keys to it)
2. Restart the script
3. Now you dont have keys to your current car anymrore

**Expected behavior**
I expected that i can still open and close my owned vehicle as its supposed to.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: About 1 or 2 weeks ago
 - Are you using custom resource? which ones? qb-garages by JonasDev17
 - Have you renamed `qb-` to something custom? no

**Additional context**

**Comment by Sharkiiie** [comment]
This is expected behavior.
When any script is restarted all of the variables will be reset. In this case, the client side KeysList table will be set back to an empty table.

**Comment by W0lv3sxD** [comment]
I need to save the keys of vehicles that are not in the garage. Im using the AdvancedParking script by Kiminaze which respawns the vehicles after server restart. When joining after server restart you cant unlock your own vehicle anymore. I need help at this as I think it could be a "bug" or a suggestion to qb-vehiclekeys.

**Comment by Sharkiiie** [comment]
This is not currently something QBCore has planned as a feature, and as I said is expected behavior.

I would suggest reaching out to the creator of that script for assistance.
Either they will need to modify their script to add compatibility, or you will need to modify their script (if able), and / or vehiclekeys.

I would suggest on server restart saving all spawned vehicles information (plates and owners, at least), then when the player loads have the server send the keys to the player. Or something similar to that.
I'm sure that's roughly how the script works already, so it shouldn't be entirely too difficult.
